### ISSUE TITLE
Incorrect subscriber count

### ISSUE THREAD

**Issue by AXVin** [valerebron/usetube#1]
When i do this:
```js
const usetube = require('usetube');
usetube.searchChannel('pokimane').then(channels => console.log(channels));
```
The nb_subscriber field seems to not show the correct amount. It is currently showing a 3 digit number only which i know that it isn't. I wanted to sort these channels according to the sub count for the search but this seems to give some unreliable stats

**Comment by valerebron** [comment]
Hi AXVin,
My bad, I forgot to format k (kilo views) an m (million views).
should be up & ready in v1.1.4.

Cheers,
Valère
