### ISSUE TITLE
Cannot read property 'continuationItemRenderer' of undefined

### ISSUE THREAD

**Issue by davidpoza** [valerebron/usetube#11]
error is triggered on youtube-grabber.js:160.

it should be something like:

```
if (typeof continuationItem !== 'undefined' && continuationItem[0]) {
   nextContinuation = continuationItem[0].continuationItemRenderer.continuationEndpoint.continuationCommand.token
}
```

**Comment by valerebron** [comment]
Hi David,

Can you tell me witch tyepscript function warn you this ?

Valère

**Comment by valerebron** [comment]
I just update usetube to 2.0.5.
Try with this version and tell me if it's ok :)
