### ISSUE TITLE
usetube.searchVideo -> videos error, terms

### ISSUE THREAD

**Issue by frabazz** [valerebron/usetube#12]
`var results = await usetube.searchVideo("titanium");`
Whenever I try to fetch results from a video search i get an error like this: search "videos error, terms: titanium"
I've used this library in the past with discord.js, but now i'm trying to intergrate it with react, and i get always this error.

**Comment by valerebron** [comment]
For now Usetube is only backend javascript consistent (commonjs & nodejs).
I'll try to put axios back & work for frontend framework (ES6 for react vue svelte or whatever).

**Comment by valerebron** [comment]
Try with usetube 2.0.5 & tell me if it works.
I will try to use it with vue-cli later.

**Comment by valerebron** [comment]
Unless you find a way to fetch youtube from client-side disabeling cors verification,
usetube is not possible in client-side.
