### ISSUE TITLE
publishedAt for searchForVideos is wrong

### ISSUE THREAD

**Issue by hamzaafridi** [valerebron/usetube#13]
I was looking at data and testing the function all publishedAt field for searchForVideos returned current timestamp.

**Comment by valerebron** [comment]
Hi hamzaafridi,
I have just published usetube 2.1.0, It should fix formatVideo.
Few exeptions were needed but thanks for the PR it helped me.
Again, If you have feedback I'll be glad to check it.

Cheers !
