### ISSUE TITLE
Search Result dates incorrect

### ISSUE THREAD

**Issue by towfiqi** [valerebron/usetube#16]
@valerebron The search result always returns the current date/time, instead of the video's date time.

Also, is there a way to get view count of videos in search results?

**Comment by valerebron** [comment]
@towfiqi , usetube return current date/time to fill publishedAt when returning didyoumean datas:
[https://github.com/valerebron/usetube/blob/7c2a19e4cbba9603727445114081dcc14824eb0e/src/helpers/formatVideo.ts#L110](url)

Tell me exactly witch usteube query cause current date results in your case & I'll try to fix it.

View count is plan for the next version, stay tune.

**Comment by valerebron** [comment]
should be fixed with usetube 2.1.1 !

cheers !
