### ISSUE TITLE
Include type declarations in the npm package

### ISSUE THREAD

**Issue by ipmanlk** [valerebron/usetube#2]
There aren't any type declaration files in the npm package and those should be included for using this with typescript.

**Comment by valerebron** [comment]
Hi ipmanlk !
For now typedef are in the readme,
pull request internal typedef and I'll be glad to test & integrate your code to usetube ;)

cheers,
Valère

**Comment by valerebron** [comment]
typedef are now in types/ directory

cheers,
Valère
