### ISSUE TITLE
cannot get channel videos for id but the id is right?

### ISSUE THREAD

**Issue by CodeReaper1** [valerebron/usetube#26]
I keep getting cannot get channel videos for id: (the id that is actually correct)
[test.zip](https://github.com/valerebron/usetube/files/9901780/test.zip)

**Comment by TGoC-virus** [comment]
Yes I have the same issue

**Comment by valerebron** [comment]
To both of you,
youtube website update few days ago and get channel videos was impacted.
Try version 2.20 of usetube, it should works now.
If you want to know why, here the code associated :
https://github.com/valerebron/usetube/commit/b2e820d3e3345ca6a7fc19e6ec4e941e7800fd82#diff-a40b352c214cb37657cc49be2e290385fb5d6ad30e3d2bf382913eb49d664fdf
