### ISSUE TITLE
Suggestion: Function to get all songs from a playlist

### ISSUE THREAD

**Issue by Pixel1011** [valerebron/usetube#3]
If given a playlist URL to a specific function **getPlaylist(url)** then return all the videos which are in the playlist in an array

**Comment by valerebron** [comment]
That's a good Idea !
check the code and pull request a getPlaylist(url) function :)
For now I don't have time to write this function but I can help you.

cheers,
Valère

**Comment by valerebron** [comment]
Thats finaly it.
UseTube v1.3.0 contains a getPlaylistVideos() function !

you can try it like this :
``` javascript
usetube.getPlaylistVideos('PLKuN-WEIzl_pwo3US7XyZJe1oVCD7NLwF').then(videos => { console.log(videos) })
```
Go check the readme for more details.

cheers
