### ISSUE TITLE
getVideoSubtitles is absent

### ISSUE THREAD

**Issue by 0xRaduan** [valerebron/usetube#30]
There is no getVideoSubtitles method in this library, even though it's mentioned in the README.

**Comment by valerebron** [comment]
Hi Raduan,
yes indeed I deleted here : https://github.com/valerebron/usetube/commit/edac2d68664390794d10570b22e89451e01ca7d4#diff-95df7c8ea867f3d68b4b56675f17d31a596b9e542d78e669bde7743f9823d221

And I just added before here :
https://github.com/valerebron/usetube/commit/e8e0019932d42d80147060fa9a5ad0ccc783bba9#diff-95df7c8ea867f3d68b4b56675f17d31a596b9e542d78e669bde7743f9823d221

You can get youtube video transcript from the html video page but I no longer maintain usetube.
I use youtubei: https://www.npmjs.com/package/youtubei  wich is way more completed.
they seems to manage subtitles, go check the docs : https://suspiciouslookingowl.github.io/youtubei/

cheers !

**Comment by 0xRaduan** [comment]
I see, thanks for the reply and the library, @valerebron – I will check it out.
