### ISSUE TITLE
Searching for video sometimes returns video id of "didyoumean"

### ISSUE THREAD

**Issue by Pixel1011** [valerebron/usetube#8]
Occasionally returns that which then leads my program to error with
 TypeError: Video id (didyoumean) does not match expected format (/^[a-zA-Z0-9-_]{11}$/)

**Comment by valerebron** [comment]
Yes,
if youtube believe you misstype a world, usetube give a first result with 'didyoumean' id.
This should be aside videos data, indeed.
I'ts a feature for next version.

**Comment by valerebron** [comment]
didyoumean is now aside data in v1.1.5

cheers
